/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vin
 */
public class v_AdminDaftar extends javax.swing.JFrame {

    /**
     * Creates new form v_AdminDaftar
     */
    public v_AdminDaftar() {
        initComponents();
        this.setLocationRelativeTo(this);
        tb_user.changeSelection(0, 0, true, false);
    }

    public int getSelectedRow() {
        return tb_user.getSelectedRow();
    }

    public void setTable(DefaultTableModel table) {
        this.tb_user.setModel(table);
    }

    public String getValueAt(int baris, int kolom) {
        return tb_user.getValueAt(baris, kolom).toString();
    }

    public String getId() {
        return id.getText();
    }

    public void setId(String id) {
        this.id.setText(id);
    }

    public String getNamaUser() {
        return nama.getText();
    }

    public String getAlamat() {
        return alamat.getText();
    }

    public String getJenisKelamin() {
        return kelamin.getSelectedItem().toString();
    }

    public String getStatus() {
        return status.getSelectedItem().toString();
    }

    public String getUsername() {
        return username.getText();
    }

    public String getPassword() {
        return password.getText();
    }

    public void setNamaUser(String isi) {
        this.nama.setText(isi);
    }

    public void setAlamat(String isi) {
        this.alamat.setText(isi);
    }

    public void setJenisKelamin(int status) {
        this.kelamin.setSelectedIndex(status);
    }

    public void setPassword(String isi) {
        this.password.setText(isi);
    }

    public void setStatus(int status) {
        this.status.setSelectedIndex(status);
    }

    public void setUsername(String isi) {
        this.username.setText(isi);
    }

    public void text(boolean status) {
        this.nama.setEnabled(status);
        this.alamat.setEnabled(status);
        this.username.setEnabled(status);
        this.password.setEnabled(status);
    }

    public void button(boolean status) {
        this.btn_save.setEnabled(status);
        this.btn_edit.setEnabled(status);
        this.btn_update.setEnabled(status);
        this.btn_delete.setEnabled(status);
    }

    public void addSaveListener(ActionListener e) {
        this.btn_save.addActionListener(e);
    }

    public void addDeleteListener(ActionListener e) {
        this.btn_delete.addActionListener(e);
    }

    public void addUpdateListener(ActionListener e) {
        this.btn_update.addActionListener(e);
    }

    public void addeditListener(ActionListener e) {
        this.btn_edit.addActionListener(e);
    }

    public void addBackListener(ActionListener e) {
        this.btn_kembali.addActionListener(e);
    }

    public void buttonsave(boolean status) {
        this.btn_save.setEnabled(status);
    }

    public void delete(boolean status) {
        this.btn_delete.setEnabled(status);
    }

    public void buttonedit(boolean status) {
        this.btn_edit.setEnabled(status);
    }

    public void buttonupdate(boolean status) {
        this.btn_update.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        kelamin = new javax.swing.JComboBox<String>();
        status = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_user = new javax.swing.JTable();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENDAFTARAN USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 44));

        jLabel2.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama               :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 112, 90, 22));

        jLabel3.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat            :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 152, 76, 24));

        jLabel4.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin   :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 194, -1, 22));

        jLabel5.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status   :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 234, 76, 28));

        jLabel6.setText("ID       :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 68, 76, 26));

        jLabel7.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username    :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 280, 76, 24));

        nama.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, -1));

        alamat.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, -1));

        username.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 110, -1));

        kelamin.setEditable(true);
        kelamin.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        kelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Salah Satu", "Laki-laki", "Perempuan" }));
        getContentPane().add(kelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, -1));

        status.setEditable(true);
        status.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Salah Satu ", "Produksi", "Gudang", "Logistik" }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, -1));

        tb_user.setFont(new java.awt.Font("Swis721 BT", 0, 11)); // NOI18N
        tb_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_user.setGridColor(new java.awt.Color(240, 240, 240));
        tb_user.setOpaque(false);
        tb_user.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tb_user.setShowHorizontalLines(false);
        tb_user.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tb_user);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 420, 275));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/simpan.png"))); // NOI18N
        btn_save.setBorder(null);
        btn_save.setBorderPainted(false);
        btn_save.setContentAreaFilled(false);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 360, 90, -1));

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ubah.png"))); // NOI18N
        btn_edit.setBorder(null);
        btn_edit.setBorderPainted(false);
        btn_edit.setContentAreaFilled(false);
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/update.png"))); // NOI18N
        btn_update.setBorder(null);
        btn_update.setBorderPainted(false);
        btn_update.setContentAreaFilled(false);
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hapus.png"))); // NOI18N
        btn_delete.setBorder(null);
        btn_delete.setBorderPainted(false);
        btn_delete.setContentAreaFilled(false);
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 90, -1));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluar.png"))); // NOI18N
        btn_kembali.setBorder(null);
        btn_kembali.setBorderPainted(false);
        btn_kembali.setContentAreaFilled(false);
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 190, 40));

        jLabel8.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password     :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 328, -1, -1));

        password.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 110, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 74, 67, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backgrund.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_AdminDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_AdminDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_AdminDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_AdminDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_AdminDaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kelamin;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tb_user;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
