/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Vin
 */
public class v_permintaanLogistik extends javax.swing.JFrame {

    /**
     * Creates new form v_permintaanLogistik
     */
    public v_permintaanLogistik() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JComboBox<String> getCabang() {
        return cabang;
    }

    public JTable getTableMinta() {
        return tb_minta;
    }

    public void getBtnPesan(ActionListener a) {
        btn_pesan.addActionListener(a);
    }

    public void getBtnBatal(ActionListener a) {
        btn_batal.addActionListener(a);
    }

    public void getBtnCetak(ActionListener a) {
        btn_cetak.addActionListener(a);
    }

    public void getBtnKembali(ActionListener a) {
        btn_kembali.addActionListener(a);
    }

    public void setComboCabang(String[] comboCabang) {
        for (String a : comboCabang) {
            this.cabang.addItem(a);
        }
    }

    public JTextField getSosro() {
        return sosro;
    }

    public JTextField getFruittea() {
        return fruittea;
    }

    public JTextField getTebs() {
        return tebs;
    }

    public JTextField getStee() {
        return stee;
    }

    public JDateChooser getTanggal() {
        return tanggal;
    }

    public void hapus() {
        cabang.setSelectedIndex(0);
        sosro.setText("");
        fruittea.setText("");
        tebs.setText("");
        stee.setText("");
//        tanggal.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sosro = new javax.swing.JTextField();
        fruittea = new javax.swing.JTextField();
        tebs = new javax.swing.JTextField();
        stee = new javax.swing.JTextField();
        cabang = new javax.swing.JComboBox<>();
        btn_pesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_minta = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        tanggal = new com.toedter.calendar.JDateChooser();
        btn_cetak = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Permintaan Stok Logistik");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 440, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cabang   :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sosro      :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fruittea  :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tebs       :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("S-Tee     :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        sosro.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        getContentPane().add(sosro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 30));

        fruittea.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        getContentPane().add(fruittea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 120, 30));

        tebs.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        getContentPane().add(tebs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, 30));

        stee.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        getContentPane().add(stee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, 30));

        cabang.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        cabang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        getContentPane().add(cabang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, 30));

        btn_pesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pesan.png"))); // NOI18N
        btn_pesan.setBorder(null);
        btn_pesan.setBorderPainted(false);
        btn_pesan.setContentAreaFilled(false);
        getContentPane().add(btn_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 200, 50));

        tb_minta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_minta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, 308));

        jLabel7.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Pesan :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluar.png"))); // NOI18N
        btn_kembali.setBorder(null);
        btn_kembali.setBorderPainted(false);
        btn_kembali.setContentAreaFilled(false);
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 190, -1));

        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reset.png"))); // NOI18N
        btn_batal.setBorder(null);
        btn_batal.setBorderPainted(false);
        btn_batal.setContentAreaFilled(false);
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 200, 50));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 150, 30));

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backgrund.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
    
    }//GEN-LAST:event_btn_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_permintaanLogistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_permintaanLogistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_permintaanLogistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_permintaanLogistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_permintaanLogistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_pesan;
    private javax.swing.JComboBox<String> cabang;
    private javax.swing.JTextField fruittea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sosro;
    private javax.swing.JTextField stee;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTable tb_minta;
    private javax.swing.JTextField tebs;
    // End of variables declaration//GEN-END:variables
}
