/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Vin
 */
public class v_produksi extends javax.swing.JFrame {

    /**
     * Creates new form v_produksi
     */
    public v_produksi() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public void suhuListener(ActionListener listener) {
        btn_suhu.addActionListener(listener);
    }

    public void phListener(ActionListener listener) {
        btn_ph.addActionListener(listener);
    }

    public void addStokListener(ActionListener listener) {
        btn_stok.addActionListener(listener);
    }

    public void kalkulasiListener(ActionListener listener) {
        btn_kalkulasi.addActionListener(listener);
    }

    public void addLogout(ActionListener listener) {
        btn_logout.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_stok = new javax.swing.JButton();
        btn_ph = new javax.swing.JButton();
        btn_suhu = new javax.swing.JButton();
        btn_kalkulasi = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(790, 497));
        setPreferredSize(new java.awt.Dimension(800, 536));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 203, -1));

        btn_stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pend user.png"))); // NOI18N
        btn_stok.setBorder(null);
        btn_stok.setBorderPainted(false);
        btn_stok.setContentAreaFilled(false);
        getContentPane().add(btn_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 190, 180));

        btn_ph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan penjualan 2.png"))); // NOI18N
        btn_ph.setBorder(null);
        btn_ph.setBorderPainted(false);
        btn_ph.setContentAreaFilled(false);
        getContentPane().add(btn_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 260, 190));

        btn_suhu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/4.png"))); // NOI18N
        btn_suhu.setBorder(null);
        btn_suhu.setContentAreaFilled(false);
        getContentPane().add(btn_suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 230, 170));

        btn_kalkulasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/3.png"))); // NOI18N
        btn_kalkulasi.setBorder(null);
        btn_kalkulasi.setBorderPainted(false);
        btn_kalkulasi.setContentAreaFilled(false);
        getContentPane().add(btn_kalkulasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 180));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluar.png"))); // NOI18N
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pengaturan Suhu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 140, -1));

        jLabel3.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengauran PH");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 120, -1));

        jLabel4.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kalkulasi Pemasakan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, -1));

        jLabel5.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stok Produksi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 120, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/backgrund.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_produksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_produksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kalkulasi;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_ph;
    private javax.swing.JButton btn_stok;
    private javax.swing.JButton btn_suhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
